services:
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - 5000:8080
  recipeservice:
    image: recipeservice
    build:
      context: .
      dockerfile: RecipeService/Dockerfile
    ports:
      - 5100:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./seed-database:/docker-entrypoint-initdb.