services:
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
  recipeservice:
    image: recipeservice
    build:
      context: .
      dockerfile: RecipeService/Dockerfile
  apigateway:
    image: apiegateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 5100:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YwtnJsMdA8A9ky5XuE7QzyDZwXFyH9WHxTHt
    ports:
      - 5432:5432
    volumes:
      - ./seed-database:/docker-entrypoint-initdb.d